# Generated by Django 3.0.5 on 2020-05-14 10:21

from django.conf import settings
from django.db import migrations, models
import goodHealthApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goodHealthApp', '0004_auto_20200511_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=goodHealthApp.models.get_upload_image_dir),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='email', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='firstname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='lastname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='phone number', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'id')},
        ),
    ]
